{"uid":"c9615c0f474b988e","name":"test_mail_search","fullName":"tests.test_main.TestPageSearch#test_mail_search","historyId":"8f2ecf30b81961a8b55483fb1bb61617","time":{"start":1676288131937,"stop":1676288143475,"duration":11538},"status":"failed","statusMessage":"AssertionError: assert 'Mail.ru: поч...новости, игры' == 'Mail.ru'\n  - Mail.ru\n  + Mail.ru: почта, поиск в интернете, новости, игры","statusTrace":"self = <test_main.TestPageSearch object at 0x7f1be44698d0>\n\n    @allure.feature('Open pages')\n    @allure.story('Открывает страницу \"mail.ru\"')\n    def test_mail_search(self):\n        self.driver.get('https://mail.ru')\n        with allure.step('делаем скриншот'):\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=AttachmentType.PNG)\n>       assert self.driver.title == 'Mail.ru'\nE       AssertionError: assert 'Mail.ru: поч...новости, игры' == 'Mail.ru'\nE         - Mail.ru\nE         + Mail.ru: почта, поиск в интернете, новости, игры\n\ntests/test_main.py:41: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestPageSearch","time":{"start":1676288131937,"stop":1676288131937,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: assert 'Mail.ru: поч...новости, игры' == 'Mail.ru'\n  - Mail.ru\n  + Mail.ru: почта, поиск в интернете, новости, игры","statusTrace":"self = <test_main.TestPageSearch object at 0x7f1be44698d0>\n\n    @allure.feature('Open pages')\n    @allure.story('Открывает страницу \"mail.ru\"')\n    def test_mail_search(self):\n        self.driver.get('https://mail.ru')\n        with allure.step('делаем скриншот'):\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=AttachmentType.PNG)\n>       assert self.driver.title == 'Mail.ru'\nE       AssertionError: assert 'Mail.ru: поч...новости, игры' == 'Mail.ru'\nE         - Mail.ru\nE         + Mail.ru: почта, поиск в интернете, новости, игры\n\ntests/test_main.py:41: AssertionError","steps":[{"name":"делаем скриншот","time":{"start":1676288143245,"stop":1676288143458,"duration":213},"status":"passed","steps":[],"attachments":[{"uid":"2c2c828a7b4146b4","name":"Screenshot","source":"2c2c828a7b4146b4.png","type":"image/png","size":258046}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"_xunit_setup_method_fixture_TestPageSearch::0","time":{"start":1676288143516,"stop":1676288143516,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"story","value":"Открывает страницу \"mail.ru\""},{"name":"feature","value":"Open pages"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_main"},{"name":"subSuite","value":"TestPageSearch"},{"name":"host","value":"fv-az251-307"},{"name":"thread","value":"2240-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_main"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":5},"items":[{"uid":"3730c01004ff6634","reportUrl":"https://Yuriyvas.github.io/pythonProject5/11//#testresult/3730c01004ff6634","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52721): Max retries exceeded with url: /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26e410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676284093505,"stop":1676284093507,"duration":2}},{"uid":"c84807f3113c33a4","reportUrl":"https://Yuriyvas.github.io/pythonProject5/10//#testresult/c84807f3113c33a4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=34359): Max retries exceeded with url: /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e2380>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676278541757,"stop":1676278541759,"duration":2}},{"uid":"b9b94ad1e03345fc","reportUrl":"https://Yuriyvas.github.io/pythonProject5/6//#testresult/b9b94ad1e03345fc","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d62232b303 <unknown>\n#1 0x55d6220ffd37 <unknown>\n#2 0x55d622128157 <unknown>\n#3 0x55d622124330 <unknown>\n#4 0x55d6221654a6 <unknown>\n#5 0x55d62215c753 <unknown>\n#6 0x55d62212fa14 <unknown>\n#7 0x55d622130b7e <unknown>\n#8 0x55d62237a32e <unknown>\n#9 0x55d62237dc0e <unknown>\n#10 0x55d622360610 <unknown>\n#11 0x55d62237ec23 <unknown>\n#12 0x55d622352545 <unknown>\n#13 0x55d62239f6a8 <unknown>\n#14 0x55d62239f836 <unknown>\n#15 0x55d6223bad13 <unknown>\n#16 0x7f933c266b43 <unknown>","time":{"start":1676144196945,"stop":1676144196945,"duration":0}},{"uid":"2f243a0692c04791","reportUrl":"https://Yuriyvas.github.io/pythonProject5/5//#testresult/2f243a0692c04791","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55cff01b6303 <unknown>\n#1 0x55cfeff8ad37 <unknown>\n#2 0x55cfeffb3157 <unknown>\n#3 0x55cfeffaf330 <unknown>\n#4 0x55cfefff04a6 <unknown>\n#5 0x55cfeffe7753 <unknown>\n#6 0x55cfeffbaa14 <unknown>\n#7 0x55cfeffbbb7e <unknown>\n#8 0x55cff020532e <unknown>\n#9 0x55cff0208c0e <unknown>\n#10 0x55cff01eb610 <unknown>\n#11 0x55cff0209c23 <unknown>\n#12 0x55cff01dd545 <unknown>\n#13 0x55cff022a6a8 <unknown>\n#14 0x55cff022a836 <unknown>\n#15 0x55cff0245d13 <unknown>\n#16 0x7f2e2f424b43 <unknown>","time":{"start":1676143939065,"stop":1676143939065,"duration":0}}]},"tags":[]},"source":"c9615c0f474b988e.json","parameterValues":[]}